# Generated by Django 5.2.2 on 2025-06-08 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0005_rename_watchlist_review_watchlist_review_review_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='activbe',
            new_name='active',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='avg_rating',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='number_ratings',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
